# Generated by Django 3.1.3 on 2023-02-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('pw', models.CharField(max_length=15)),
                ('pw_1', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('t_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('p_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20)),
                ('position', models.TextField()),
                ('distance', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('t_no', models.ForeignKey(db_column='t_no', on_delete=django.db.models.deletion.CASCADE, to='pybo.thema')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('ch_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ch_name', models.TextField()),
                ('ch_to', models.CharField(max_length=10)),
                ('mem_id', models.ForeignKey(db_column='mem_id', on_delete=django.db.models.deletion.CASCADE, to='pybo.member')),
            ],
        ),
    ]
